### ISSUE TITLE
Playing on xbox/switch

### ISSUE THREAD

**Issue by antonioanerao** [arkmanager/ark-server-tools#1252]
Hello guys. Is it possible to run a server and play on xbox? I can find my server playing on steam but I can`t find my server on xbox/switch.
I've cross player enabled but not sure if I'm missing something. I will leave a copy of my docker-compose.yml

```
version: '3'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - ./ark-server:/app
      - ./ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - SERVER_MAP=${SERVER_MAP}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - UPDATE_ON_START=${UPDATE_ON_START}
      - BACKUP_ON_STOP=${BACKUP_ON_STOP}
      - PRE_UPDATE_BACKUP=${PRE_UPDATE_BACKUP}
      - WARN_ON_STOP=${WARN_ON_STOP}
      - ENABLE_CROSSPLAY=${ENABLE_CROSSPLAY}
      - DISABLE_BATTLEYE=${DISABLE_BATTLEYE}
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
```

I can see a output of args with --crossplay, just like that

``` bash
# Ark Server - Sat May 20 22:23:27 UTC 2023
# IMAGE_VERSION: '1684213291'
# RUNNING AS USER 'steam' - '1000'
# ARGS: --arkopt,-crossplay 
```
