### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by 1mathart** [arkmanager/ark-server-tools#1254]
Hello,
i would like to setup an ARK server for pc users (steam & epic games) all running with docker but i always end up with this error 
"Invalid steamcmd_user in config file".

i made this docker compose with "hermsi/ark-server" image.

```
version: "3.8"
services:

 ark:
  image: "hermsi/ark-server:latest"
  container_name: "ark"
  network_mode: "host"
  hostname: "ark"
  restart: "always"
  volumes:
    - "/opt/ark:/app"
    - "/opt/ark-backup:/home/steam/ARK-Backups"
  healthcheck:
    disable: true
  environment:
    SESSION_NAME: "X"
    SERVER_MAP: "TheIsland"
    SERVER_PASSWORD: "X
    ADMIN_PASSWORD: "X"
    MAX_PLAYERS: "8"
    UPDATE_ON_START: "false"
    BACKUP_ON_STOP: "false"
    PRE_UPDATE_BACKUP: "true"
    WARN_ON_STOP: "true"
    ENABLE_CROSSPLAY: "true"
    DISABLE_BATTLEYE: "true"
    GAME_CLIENT_PORT: "7777"
    UDP_SOCKET_PORT: "7778"
    RCON_PORT: "27020"
    SERVER_LIST_PORT: "27015"

volumes:
 steamcmd_login_volume:
  external: true
 steamcmd_volume:
  external: true
```

i don't understand what i'm doing wrong,
if someone could help me.
